### ISSUE TITLE
Wrong usage of actual and expected?

### ISSUE THREAD

**Issue by m3gg3r** [TravisCarden/behat-table-comparison#3]
Hi there!

I think there is a problem with wrong usage of actual and expected in the following code:
https://github.com/TravisCarden/behat-table-comparison/blob/master/src/BehatTableComparison/TableEqualityAssertion.php (Line 186 ff)
`protected function assertHeader()
    {
        $expected_header = $this->getExpectedHeader();
        if (empty($expected_header)) {
            return;
        }
        $actual_header = $this->getExpected()->getRow(0);
        if ($expected_header === $actual_header) {
            return;
        }
        $message = [
            '--- Expected header',
            (new TableNode([$expected_header]))->getTableAsString(),
            '+++ Given',
            (new TableNode([$actual_header]))->getTableAsString(),
        ];
        throw new \LogicException(implode(PHP_EOL, $message));
    }`

It should be
`$actual_header = $this->getActual()->getRow(0);`
instead of
`$actual_header = $this->getExpected()->getRow(0);`

Or am i thinking something wrong?

**Comment by TravisCarden** [comment]
Hi, @m3gg3r! Thank you for the issue. I'm terribly sorry for the extremely late response. I just happened to visit this repo and realized I wasn't "watching" it.

At first glance, your concern seems valid. But upon closer inspection, you'll realize that the method isn't comparing the expected data with the actual data. It's comparing the header row of the "expected" _table_ with the header row the assertion expects to be provided. I admit it's confusing, and I had to think about it for a minute. But it is correct as it is, as evidenced by the fact that making the change you propose causes the tests to fail.

Thanks again. 😃
